# Generated by Django 2.2.1 on 2019-06-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=13)),
                ('color', models.CharField(choices=[('BLK', 'Black'), ('WHT', 'White'), ('BLU', 'Blue'), ('RED', 'Red')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SlotDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parkingLot.CarDetails')),
            ],
        ),
    ]
