# Generated by Django 2.2.1 on 2019-06-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0002_auto_20190601_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotdetails',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='slotdetails',
            name='carId',
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('BLUE', 'Blue'), ('RED', 'Red')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='slotdetails',
            name='registration_number',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
