# Generated by Django 2.2.1 on 2019-06-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0004_auto_20190604_0100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotDetails',
        ),
    ]
