# Generated by Django 2.2.1 on 2019-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0007_slotdetails_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetails',
            name='registration_number',
            field=models.CharField(default='NULL', max_length=13),
        ),
    ]
