# Generated by Django 2.2.1 on 2019-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0008_auto_20190604_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='slotdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
