# Generated by Django 2.2.1 on 2019-06-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0009_auto_20190604_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdetails',
            name='color',
        ),
    ]
