# Generated by Django 2.2.1 on 2019-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0010_remove_slotdetails_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdetails',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('BLUE', 'Blue'), ('RED', 'Red')], default='NULL', max_length=5),
        ),
    ]
