# Generated by Django 2.2.1 on 2019-06-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0011_slotdetails_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotDetails',
        ),
    ]
