# Generated by Django 2.2.1 on 2019-06-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0013_cardetails_slotdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
