# Generated by Django 2.2.1 on 2019-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingLot', '0014_delete_cardetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetails',
            name='color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('BLUE', 'Blue'), ('RED', 'Red')], default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='slotdetails',
            name='registration_number',
            field=models.CharField(default=None, max_length=13, null=True),
        ),
    ]
